name: Build and Push

on:
  push:
    branches:
      - "master"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Declare variables
        id: vars
        shell: bash
        run: |
          echo "::set-output name=tags_list::oyelowo/docker-kafka-kraft:$(echo ${GITHUB_SHA} | cut -c1-12),moeenz/docker-kafka-kraft:latest"

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.vars.outputs.tags_list }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
