apiVersion: v1
kind: ConfigMap
data:
  LOCATION_DB_USERNAME: "ct_admin"
  LOCATION_DB_NAME: "location"
  # LOCATION_DB_HOST: "postgres-location"
  LOCATION_DB_HOST: "postgres-location.default.svc.cluster.local"
  LOCATION_DB_PORT: "5434"
  PERSON_DB_USERNAME: "ct_admin"
  PERSON_DB_NAME: "person"
  # PERSON_DB_HOST: "postgres-person" # Service name
  PERSON_DB_HOST: "postgres-person.default.svc.cluster.local"
  PERSON_DB_PORT: "5433"
  # API_PERSON_HOST: udaconnect-api-person # simple service name for connecting within same namepsace
  API_PERSON_HOST: udaconnect-api-person.default.svc.cluster.local
  API_PERSON_PORT: "50052"
  #API_LOCATION_HOST: udaconnect-api-location
  API_LOCATION_HOST: udaconnect-api-location.default.svc.cluster.local
  API_LOCATION_PORT: "50051"
  KAFKA_HOST: kafka-svc.kafka-kraft.svc.cluster.local
  KAFKA_PORT: "9092"
metadata:
  name: db-env

