kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-location-volume
  labels:
    type: local
    app: postgres-location
spec:
  storageClassName: manual
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/location/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres-location
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-location
  labels:
    app: postgres-location
spec:
  type: NodePort
  selector:
    app: postgres-location
  ports:
   - name: "5434"
     port: 5434
     targetPort: 5432
     nodePort: 30011
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-location
spec:
  serviceName: postgres-location
  replicas: 1
  selector:
    matchLabels:
      app: postgres-location
  template:
    metadata:
      labels:
        app: postgres-location
    spec:
      containers:
        - name: postgres-location
          image: postgis/postgis:12-2.5-alpine
          imagePullPolicy: "IfNotPresent"
          resources:
            requests:
              memory: "128Mi"
              cpu: "64m"
            limits:
              memory: "256Mi"
              cpu: "256m"
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: db-env
                key: LOCATION_DB_USERNAME
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: db-env
                key: LOCATION_DB_NAME
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdb-location
      volumes:
        - name: postgresdb-location
          persistentVolumeClaim:
            claimName: postgres-pv-claim
