apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-api
  name: udaconnect-api
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30001
  selector:
    service: udaconnect-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-api
  name: udaconnect-api
spec:
  replicas: 2
  selector:
    matchLabels:
      service: udaconnect-api
  template:
    metadata:
      labels:
        service: udaconnect-api
    spec:
      containers:
      - image: oyelowo/udaconnect-api:latest
        name: udaconnect-api
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "64m"
          limits:
            memory: "256Mi"
            cpu: "256m"
        env:
        - name: API_PERSON_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: API_PERSON_HOST
        - name: API_PERSON_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: API_PERSON_PORT
        - name: API_LOCATION_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: API_LOCATION_HOST
        - name: API_LOCATION_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: API_LOCATION_PORT
        # - name: API_LOCATION_HOST
        #   value: udaconnect-api-location
        # - name: API_LOCATION_PORT
        #   value: "50051"
       
      restartPolicy: Always
