apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-api-person
    app: udaconnect-api-person
  name: udaconnect-api-person
spec:
  ports:
  - name: "50052"
    port: 50052
    targetPort: 50052
    nodePort: 30002
  selector:
    service: udaconnect-api-person
    app: udaconnect-api-person
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-api-person
    app: udaconnect-api-person
  name: udaconnect-api-person
spec:
  replicas: 2
  selector:
    matchLabels:
      service: udaconnect-api-person
      app: udaconnect-api-person
  template:
    metadata:
      labels:
        service: udaconnect-api-person
        app: udaconnect-api-person
    spec:
      containers:
      - image: oyelowo/udaconnect-person:latest
        name: udaconnect-api-person
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "64m"
          limits:
            memory: "256Mi"
            cpu: "256m"
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: PERSON_DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: PERSON_DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: PERSON_DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: PERSON_DB_PORT
      restartPolicy: Always
