apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-app
    app: udaconnect-app
  name: udaconnect-app
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
    nodePort: 30000
  selector:
    service: udaconnect-app
    app: udaconnect-app
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-app
    app: udaconnect-app
  name: udaconnect-app
spec:
  replicas: 3
  selector:
    matchLabels:
      service: udaconnect-app
      app: udaconnect-app
    strategy:
  # rollingUpdate:
  #   maxSurge: 25%
  #   maxUnavailable: 25%
  # type: RollingUpdate
  template:
    metadata:
      labels:
        service: udaconnect-app
        app: udaconnect-app
    spec:
      containers:
      - image: oyelowo/udaconnect-frontend:latest
        name: udaconnect-app
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "64m"
          limits:
            memory: "256Mi"
            cpu: "256m"
      restartPolicy: Always
