apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-api-location
  name: udaconnect-api-location
spec:
  ports:
  - name: "50051"
    port: 50051
    targetPort: 50051
    nodePort: 30003
  selector:
    service: udaconnect-api-location
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-api-location
  name: udaconnect-api-location
spec:
  replicas: 2
  selector:
    matchLabels:
      service: udaconnect-api-location
  template:
    metadata:
      labels:
        service: udaconnect-api-location
    spec:
      containers:
      - image: oyelowo/udaconnect-location:latest
        name: udaconnect-api-location
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "64m"
          limits:
            memory: "256Mi"
            cpu: "256m"
        env:
        - name: API_PERSON_HOST
          value: udaconnect-api-person
        - name: API_PERSON_PORT
          value: "50052"
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: LOCATION_DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: LOCATION_DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: LOCATION_DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: LOCATION_DB_PORT
      restartPolicy: Always
