version: "3"

services:
  # api:
  #   build: api
  #   command: ["flask", "run", "--host=0.0.0.0"]
  #   volumes:
  #     - ./api:/backend
  #   environment:
  #     - FLASK_ENV=development
  #     - FLASK_APP=app.py
  #   ports:
  #     - "5000:5000"
  kafka-kruft:
    build: docker/
    environment:
      - REPLICAS=3
      - SERVICE=kafka-svc
      - NAMESPACE=kafka-kraft
      - SHARE_DIR=/mnt/kafka
      #- FLASK_ENV=development
      #- FLASK_APP=app.py
    ports:
      - "9093:9092"
    volumes:
      - /mnt/kafka

volumes:
  dbscripts:
    # external: false
